Repository the-NDD/Gomterview-FE, pull requests merged in 2024-01, with the labels that each got.

#4 [NDD-388] webpack -> vite로 마이그레이션 (3h)
  .babelrc
  .eslintrc.json
  .githooks/pre-commit
  .gitignore
  .husky/pre-commit
  index.html
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/UnknownErrorBoundary.tsx
  src/constants/api.ts
  src/index.tsx
  src/page/errorPage/Loader.tsx
  src/routes/interviewVideoPublicLoader.ts
  src/routes/myPageLoader.ts
  src/types/type.d.ts
  src/types/vite-env.d.ts
  src/utils/getAPIResponseData.ts
  src/utils/logAPIErrorToSentry.ts
  src/utils/record.ts
  src/utils/redirectToGoogleLogin.ts
  src/vite-env.d.ts
  tsconfig.json
  vite.config.ts
  webpack.config.js
Labels: enhancement, feature

#3 [NDD-387] client에서 영상의 0초 시점에 대해 썸네일을 생성하도록 하는 로직을 추가 (3h/3h)
  src/apis/idrive.ts
  src/constants/api.ts
  src/hooks/useUploadToIdrive.ts
  src/types/video.ts
  src/utils/record.ts
Labels: feature

#5 [NDD-400] progress bar 현재 페이지 깜빡임 추가 및 chip 컴포넌트 추가 (2h/2h)
  src/components/common/ProgressStepBar/ProgressStepBarItem.tsx
  src/components/foundation/Chip/Chip.tsx
  src/page/interviewSettingPage/index.tsx
  src/styles/_colors.ts
  src/types/utils.ts
Labels: feature

#6 [NDD-380] 마이페이지 영상 삭제 이슈 해결 (1h/2h)
  src/components/myPage/MyPageTabs.tsx
  src/components/myPage/TabPanel/VideoListTabPanel.tsx
  src/hooks/apis/mutations/useDeleteVideoMutation.ts
  src/hooks/apis/queries/useVideoListQuery.ts
Labels: bug, enhancement

#9 [NDD-410] Interview 로직 리팩토링 (8h/8h)
  package-lock.json
  src/components/interviewPage/InterviewFooter/AnswerToggleButton.tsx
  src/components/interviewPage/InterviewFooter/InterviewExitButton.tsx
  src/components/interviewPage/InterviewFooter/InterviewFooter.tsx
  src/components/interviewPage/InterviewFooter/NextButton.tsx
  src/components/interviewPage/InterviewFooter/RecordControlButton.tsx
  src/components/interviewPage/InterviewMain/InterviewMain.tsx
  src/components/interviewPage/InterviewMain/InterviewQuestion.tsx
  src/components/interviewPage/InterviewModal/RecordStartModal.tsx
  src/components/interviewSettingPage/VideoSettingPage/AudioSelectMenu.tsx
  src/components/interviewSettingPage/VideoSettingPage/VideoSelectMenu.tsx
  src/hooks/pages/Interview/useInterview.ts
  src/hooks/useDevice.ts
  src/hooks/useMedia.tsx
  src/page/interviewPage/index.tsx
Labels: enhancement, feature

#10 [NDD-411] 곰터뷰 서비스의 Service Tour 기능을 개발합니다 (13h/13h)
  package-lock.json
  package.json
  src/atoms/interview.ts
  src/atoms/serviceTour.ts
  src/components/common/QuestionSelectionBox/QuestionAccordionList.tsx
  src/components/common/ServiceTourStep/ServiceTourStep.tsx
  src/components/common/index.ts
  src/components/interviewPage/InterviewFooter/InterviewFooter.tsx
  src/components/interviewPage/InterviewFooter/RecordControlButton.tsx
  src/components/interviewPage/InterviewHeader/RecordStatus.tsx
  src/components/interviewPage/InterviewHeader/RecordTimer.tsx
  src/components/interviewPage/InterviewMain/InterviewQuestion.tsx
  src/components/interviewPage/InterviewServiceTour.tsx
  src/components/interviewPage/index.ts
  src/components/interviewSettingPage/InterviewSettingContentLayout.tsx
  src/components/interviewSettingPage/ServiceTour/QuestionSelectPageServiceTour.tsx
  src/components/interviewSettingPage/ServiceTour/RecordPageServiceTour.tsx
  src/components/interviewSettingPage/ServiceTour/TermPageServiceTour.tsx
  src/components/interviewSettingPage/ServiceTour/VideoSettingPageServiceTour.tsx
  src/components/interviewSettingPage/index.ts
  src/components/landingPage/LadingPageServiceTour.tsx
  src/components/landingPage/ServiceTourNoticeDialog.tsx
  src/hooks/pages/Interview/useInterview.ts
  src/page/LandingPage/index.tsx
  src/page/interviewPage/index.tsx
  src/page/interviewSettingPage/QuestionSettingPage.tsx
  src/page/interviewSettingPage/RecordSettingPage.tsx
  src/page/interviewSettingPage/ServiceTermsPage.tsx
  src/page/interviewSettingPage/VideoSettingPage.tsx
  src/styles/_global.ts
Labels: enhancement, feature
